export enum EscolaridadeType {
    ENSINO_FUNDAMENTAL_INCOMPLETO,
    ENSINO_FUNDAMENTAL_COMPLETO,
    ENSINO_MEDIO_INCOMPLETO,
    ENSINO_MEDIO_COMPLETO,
    FORMACAO_TECNICA,
    ENSINO_SUPERIOR,
    POS_GRADUACAO,
    MESTRADO,
    DOUTORADO,
}
